//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//


@interface Message : NSObject

@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(nonatomic) unsigned long long number; // @synthesize number=_number;
@property(copy, nonatomic) NSString *ID; // @synthesize ID=_ID;
@end

